#!/usr/bin/env bash

WORKSPACEDIR="$(mktemp -d -p /var/tmp baseimg-tmp.XXXXXX)"
IMAGE_TAG=$1
DOCKER_REGISTRY=$2
DOCKER_USER=$3
DOCKER_PWD=$4

apt-get update && apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

apt-get update && apt-get install -y multistrap docker-ce docker-ce-cli containerd.io
systemctl start docker
systemctl enable docker

cat << EOF | tee ${WORKSPACEDIR}/xenial.conf
[General]
arch=amd64
directory=ubuntu_xenial
cleanup=true
noauth=false
explicitsuite=false
unpack=true
bootstrap=xenial xenial-updates xenial-security

[xenial]
packages=apt kmod iproute2 curl wget
source=http://archive.ubuntu.com/ubuntu
keyring=ubuntu-keyring
suite=xenial
components=main multiverse restricted universe

[xenial-updates]
packages=apt kmod iproute2 curl wget
source=http://archive.ubuntu.com/ubuntu
suite=xenial-updates
components=main multiverse restricted universe

[xenial-security]
packages=apt kmod iproute2 curl wget
source=http://archive.ubuntu.com/ubuntu
suite=xenial-security
components=main multiverse restricted universe
EOF

cat << EOF | tee ${WORKSPACEDIR}/bionic.conf
[General]
arch=amd64
directory=ubuntu_bionic
cleanup=true
noauth=false
explicitsuite=false
unpack=true
bootstrap=bionic bionic-updates bionic-security

[bionic]
packages=apt kmod iproute2 curl wget
source=http://archive.ubuntu.com/ubuntu
keyring=ubuntu-keyring
suite=bionic
components=main multiverse restricted universe

[bionic-updates]
packages=apt kmod iproute2 curl wget
source=http://archive.ubuntu.com/ubuntu
suite=bionic-updates
components=main multiverse restricted universe

[bionic-security]
packages=apt kmod iproute2 curl wget
source=http://archive.ubuntu.com/ubuntu
suite=bionic-security
components=main multiverse restricted universe
EOF

cat << EOF | tee ${WORKSPACEDIR}/focal.conf
[General]
arch=amd64
directory=ubuntu_focal
cleanup=true
noauth=false
explicitsuite=false
unpack=true
bootstrap=focal focal-updates focal-security

[focal]
packages=apt kmod iproute2 curl wget
source=http://archive.ubuntu.com/ubuntu
keyring=ubuntu-keyring
suite=focal
components=main multiverse restricted universe

[focal-updates]
packages=apt kmod iproute2 curl wget
source=http://archive.ubuntu.com/ubuntu
suite=focal-updates
components=main multiverse restricted universe

[focal-security]
packages=apt kmod iproute2 curl wget
source=http://archive.ubuntu.com/ubuntu
suite=focal-security
components=main multiverse restricted universe
EOF

cd ${WORKSPACEDIR}
multistrap -f ${WORKSPACEDIR}/${IMAGE_TAG}.conf
tar -C ubuntu_${IMAGE_TAG} -c . | docker import - "${DOCKER_REGISTRY}/${DOCKER_USER}/ubuntu:${IMAGE_TAG}"

docker login ${DOCKER_REGISTRY} -u ${DOCKER_USER} -p ${DOCKER_PWD}
docker push ${DOCKER_REGISTRY}/${DOCKER_USER}/ubuntu:${IMAGE_TAG}
