#!/usr/bin/env bash

set -e

DOCKER_REGISTRY=$1
DOCKER_USER=$2
DOCKER_PWD=$3

# Create a folder for our new root structure
WORKSPACEDIR="$(mktemp -d -p /var/tmp baseimg-tmp.XXXXXX)"
centos_root=${WORKSPACEDIR}/rootfs
mkdir -p $centos_root

# initialize rpm database
rpm --root $centos_root --initdb

# download and install the centos-release package, it contains our repository sources
yum reinstall --downloadonly --downloaddir . centos-release
rpm --nodeps --root $centos_root -ivh centos-release*.rpm
rpm --root $centos_root --import  $centos_root/etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

# install yum without docs and install only the english language files during the process
yum -y --installroot=$centos_root --setopt=tsflags='nodocs' --setopt=override_install_langs=en_US.utf8 install yum tar gzip

# configure yum to avoid installing of docs and other language files than english generally
sed -i "/distroverpkg=centos-release/a override_install_langs=en_US.utf8\ntsflags=nodocs" $centos_root/etc/yum.conf

# chroot to the environment and install some additional tools
cp /etc/resolv.conf $centos_root/etc
chroot $centos_root /bin/bash <<EOF
mknod -m 666 /dev/random c 1 8
mknod -m 666 /dev/urandom c 1 9
yum update -y
yum clean all
EOF
rm -f $centos_root/etc/resolv.conf

# create docker image
tar -C $centos_root -c . | docker import - "${DOCKER_REGISTRY}/${DOCKER_USER}/centos:7"

docker login ${DOCKER_REGISTRY} -u ${DOCKER_USER} -p ${DOCKER_PWD}
docker push ${DOCKER_REGISTRY}/${DOCKER_USER}/centos:7

